#!/usr/bin/csh
#
###########################################################################
#
# This file is part of Celera Assembler, a software program that
# assembles whole-genome shotgun reads into contigs and scaffolds.
# Copyright (C) 1999-2004, Applera Corporation. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received (LICENSE.txt) a copy of the GNU General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###########################################################################
#
#=======================================================================
# Script for properly invoking the awk script which
# extracts a Celera I/O message of a given type matching
# a given identifying search target
#
# Usage:
#        extractMSG <3-code> <search-target> <input_file>  > output_file
#
#  e.g.  extractMSG IUM acc:4575 a004.cns > 4575.ium
#
#  Author: Karin A. Remington
#=======================================================================

if ( $#argv != 3 ) then
  echo
  echo "Usage: extractMSG 3-code search_target input_file "
  echo
  exit
endif
gawk -v type=$1 search=$2 -f $AS_ROOT/bin/AS_UTL_extractMSG.awk $3
