
/******************************************************************************
 *
 *  This file is part of 'sequence' and/or 'meryl', software programs for
 *  working with DNA sequence files and k-mers contained in them.
 *
 *  Modifications by:
 *
 *    Brian P. Walenz beginning on 2018-FEB-26
 *      are a 'United States Government Work', and
 *      are released in the public domain
 *
 *  File 'README.license' in the root directory of this distribution contains
 *  full conditions and disclaimers.
 */

#ifndef MERYL_H
#define MERYL_H

#include "AS_global.H"

#include "merylInput.H"
#include "merylOp.H"
#include "merylCountArray.H"

#include <stack>
#include <vector>
#include <algorithm>
using namespace std;

#undef DEBUG_COUNT

#endif  //  MERYL_H
