
/******************************************************************************
 *
 *  This file is part of canu, a software program that assembles whole-genome
 *  sequencing reads into contigs.
 *
 *  This software is based on:
 *    'Celera Assembler' r4587 (http://wgs-assembler.sourceforge.net)
 *    the 'kmer package' r1994 (http://kmer.sourceforge.net)
 *
 *  Except as indicated otherwise, this is a 'United States Government Work',
 *  and is released in the public domain.
 *
 *  File 'README.licenses' in the root directory of this distribution
 *  contains full conditions and disclaimers.
 */

#ifndef OVERLAPINCORE_H
#define OVERLAPINCORE_H

#include "runtime.H"
#include "system.H"

#include "types.H"
#include "bits.H"

#include "sqStore.H"
#include "sqCache.H"
#include "ovStore.H"

#include "prefixEditDistance.H"

#include "overlapInCore-hashReadInfo.H"
#include "overlapInCore-kmerRef.H"
#include "overlapInCore-hashFunctions.H"
#include "overlapInCore-hashTable.H"

#include "overlapInCore-Constants.H"
#include "overlapInCore-Overlaps.H"

#include "overlapInCore-keyIterator.H"



#endif  //  OVERLAPINCORE_H
