all:
	curl https://wiki.dnanexus.com/images/files/dnanexus-upload-agent-1.5.30-linux.tar.gz | tar zxvf - && mv dnanexus-upload-agent-1.5.30-linux/ua resources/bin/ && rm -rf dnanexus-upload-agent-1.5.30-linux*
