#! /bin/ksh
#
###########################################################################
#
# This file is part of Celera Assembler, a software program that 
# assembles whole-genome shotgun reads into contigs and scaffolds.
# Copyright (C) 1999-2004, Applera Corporation. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received (LICENSE.txt) a copy of the GNU General Public 
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###########################################################################
#
#
# Usage: $ display-repeats file.cms
# where file.cms is the comments file produced from "$ celsim file.sim".
#
# Purpose: To augment a celamy output file with the repeat regions
# of the genome.
#
# Actions:
# Creates set of "standard" .cam files for celamy to display repeat
# elements together with fragments.
# CAMFILE=${1%%.cms}.cam ; export CAMFILE
CAMFILE=$1.cam ; export CAMFILE
echo $1 "$CAMFILE"
AS_BIN=$AS_ROOT/bin
#
$AS_BIN/show-feature "B" $1 8f8f8f alu >> ${CAMFILE}     # grey alus
$AS_BIN/show-feature "C" $1 ff00ff LINE >> ${CAMFILE}    # magenta LINE's
$AS_BIN/show-feature "E" $1 ff0000 shrttan >> ${CAMFILE} # red short tandems
$AS_BIN/show-feature "G" $1 ff4f00 medtan >> ${CAMFILE}  # brown medium tandems
$AS_BIN/show-feature "I" $1 ff004f longtan >> ${CAMFILE} # dark red long tandems
$AS_BIN/show-feature "J" $1 00ff00 gene >> ${CAMFILE}    # green genes
$AS_BIN/show-feature "K" $1 008f00 trans >> ${CAMFILE}   # dark green translocations
#

#cat b1.cam b2.cam b3.cam b4.cam b5.cam b6.cam b7.cam > ${1%%.cam}.cam0
#rm -f b1.cam b2.cam b3.cam b4.cam b5.cam b6.cam
#
