
/******************************************************************************
 *
 *  This file is part of canu, a software program that assembles whole-genome
 *  sequencing reads into contigs.
 *
 *  This software is based on:
 *    'Celera Assembler' (http://wgs-assembler.sourceforge.net)
 *    the 'kmer package' (http://kmer.sourceforge.net)
 *  both originally distributed by Applera Corporation under the GNU General
 *  Public License, version 2.
 *
 *  Canu branched from Celera Assembler at its revision 4587.
 *  Canu branched from the kmer project at its revision 1994.
 *
 *  Modifications by:
 *
 *  File 'README.licenses' in the root directory of this distribution contains
 *  full conditions and disclaimers for each license.
 */

#ifndef REVERSECOMPLEMENT_H
#define REVERSECOMPLEMENT_H

#include "AS_global.H"

void  reverseComplementSequence(char *seq, int len);
char *reverseComplementCopy(char *seq, int len);

template<typename qvType>
void  reverseComplement(char *seq, qvType *qlt, int len);

#endif
