#!/usr/local/bin/bash
#
###########################################################################
#
# This file is part of Celera Assembler, a software program that 
# assembles whole-genome shotgun reads into contigs and scaffolds.
# Copyright (C) 1999-2004, Applera Corporation. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received (LICENSE.txt) a copy of the GNU General Public 
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###########################################################################
#
#
# test change
# Usage: $ chmod a+x $AS_ROOT/scripts/run_test
#        $ bsub -K < $AS_ROOT/scripts/run_test
#
# Purpose: Perform periodic test runs.
#
# The source code that is tagged as "under test" for this phase of testing
# is compiled and run on the genome list specified.
#
##########################################################################
#
# The following are the independent environmental variables.
# You may have to change these settings.
#
# Did you set your environmental variable LSB_HOSTS?  
# If not, use the next lines.
#
#BSUB -J do_DAILY
#BSUB -P AssemblyTest      # the default project name
#BSUB -o lsf_output
#
DEFAULT_TAG=AS_PRIV_ASSEMBLER_BUILT
#
PRIOR_TAG=
RUN_TAG=DAILY
GENOME_LIST="a006 a005 a004 hflu001 adh3"
#
#PRIOR_TAG=DAILY
#RUN_TAG=WEEKLY
#GENOME_LIST="a003 ww001"
#
#RUN_TAG=BIG
#GENOME_LIST="a006 a005 a004 hflu001 adh3 a003 ww001 ww001_1_1 ww001_1_2"
#
#PRIOR_TAG=WEEKLY
#PRIOR_TAG=DROS
#RUN_TAG=DROS
#GENOME_LIST="drosophila"
#
DEFAULT_TAG=AS_PRIV_ASSEMBLER_BUILT
AS_PERIODIC_PATH=/data/assembly2/testcases/periodic
AS_RELEASE_PATH=${AS_PERIODIC_PATH}/${RUN_TAG}.dir
AS_DATA_PATH=${AS_RELEASE_PATH}
#
# get_test needs AS_RELEASE_PATH, AS_DATA_PATH,
#                RUN_TAG, PRIOR_TAG, and DEFAULT_TAG defined.
# run_test needs AS_RELEASE_PATH, AS_DATA_PATH,
#                RUN_TAG, and GENOME_LIST defined.
#
export AS_RELEASE_PATH
export AS_DATA_PATH
export DEFAULT_TAG
export PRIOR_TAG
export RUN_TAG
export GENOME_LIST
#
bsub \
 -P AssemblyTest -J Assembler_Get_${RUN_TAG} \
 -o ${AS_PERIODIC_PATH}/${RUN_TAG}.output \
 < ${AS_ROOT}/scripts/get_test
#
bsub -w Assembler_Get_${RUN_TAG} \
 -P AssemblyTest -J Assembler_Run_${RUN_TAG} \
 -o ${AS_PERIODIC_PATH}/${RUN_TAG}.output \
 < ${AS_ROOT}/scripts/run_test
#
bsub -b 01:01 -w Assembler_Run_${RUN_TAG} \
 -P AssemblyTest -J Assembler_Do_${RUN_TAG} \
 -o ${AS_PERIODIC_PATH}/${RUN_TAG}.output \
< ${AS_ROOT}/scripts/do_${RUN_TAG}
#
exit 0
