#! /bin/ksh
#
###########################################################################
#
# This file is part of Celera Assembler, a software program that 
# assembles whole-genome shotgun reads into contigs and scaffolds.
# Copyright (C) 1999-2004, Applera Corporation. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received (LICENSE.txt) a copy of the GNU General Public 
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###########################################################################
#
#
# Usage: $ Install_Nuggetizer1_0
#
# Purpose: Installs and test drives the Nuggetizer1_0.
#
# These are the release dependent environmental variables.
# You may have to change these settings.
export CDS_VERSION=Nuggetizer1_0
export RELEASE_PATH=/work/assembly/asteam/releases/$CDS_VERSION
export TEST_DATA_PATH=/data/assembly/testcases/$CDS_VERSION
# A genome to check the executable and setup.
GENOME=a004
#
# ***BY THE WAY****
# The relevant documents are in:
# $RELEASE_PATH/cds/doc/Assembler/Programs/Nuggetizer.
# Microsoft junk will not automagicly detect that there is a 
# new version of your document caused by the "cvs checkout".
# Microsoft junk caches a copy of the documents in some squirrelly 
# directory. Be very sure that you are looking at the correct document.
#
# Contact: Clark Mobarry, x3125
# Written: 1999/04/20
# Expires: 1999/05/28
#
####################################################################
#
# Environment setup
export CVSROOT=/cm/cvs
export CVSREAD
#
#
mkdir -p $RELEASE_PATH
cd $RELEASE_PATH
cvs checkout -r AS_PRIV_$CDS_VERSION cds/SEP cds/AS
cat <<EOF >README
This directory was populated by the CVS command:
$ cds checkout -r AS_PRIV_$CDS_VERSION cds/SEP cds/AS
EOF
#
export AS_ROOT=$RELEASE_PATH/cds/AS
export SEP_PATH=$RELEASE_PATH/cds/SEP
export PATH=$AS_ROOT/scripts:$AS_ROOT/bin:$PATH
#
echo "Compling started"
cd $AS_ROOT/src
gmake all install
echo "Compiling done"
echo "Installation done"
#
#
####################################################################
#
mkdir -p $TEST_DATA_PATH/$GENOME
cd $TEST_DATA_PATH/$GENOME
pwd
cp $AS_ROOT/testcases/AS_specfiles/$GENOME.sim .
ls -la
env
#
#
celsim $GENOME.sim
nuggetizer $GENOME
#
############################################################
