#! /bin/ksh
#
###########################################################################
#
# This file is part of Celera Assembler, a software program that 
# assembles whole-genome shotgun reads into contigs and scaffolds.
# Copyright (C) 1999-2004, Applera Corporation. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received (LICENSE.txt) a copy of the GNU General Public 
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###########################################################################
#
#
# Usage: $ SetupNuggetizer1_0
#
# Purpose: Sets environment for Nuggetizer1_0.
#
# These are the release dependent environmental variables.
# You may have to change these settings.
CDS_VERSION=Nuggetizer1_0 ; export CDS_VERSION
RELEASE_PATH=/work/assembly/asteam/releases/$CDS_VERSION ; export RELEASE_PATH
#
# ***BY THE WAY****
# The relevant documents are in:
# $RELEASE_PATH/cds/doc/Assembler/Programs/Nuggetizer.
# Microsoft junk will not automagicly detect that there is a 
# new version of your document caused by the "cvs checkout".
# Microsoft junk caches a copy of the documents in some squirrelly 
# directory. Be very sure that you are looking at the correct document.
#
# Contact: Clark Mobarry, x3125
# Written: 1999/04/20
# Expires: 1999/05/28
#
####################################################################
#
# Environment setup
CVSROOT=/cm/cvs ; export CVSROOT
export CVSREAD
#
#
#( cd $RELEASE_PATH ; cvs update -r AS_PRIV_$CDS_VERSION cds/SEP cds/AS )
#
AS_ROOT=$RELEASE_PATH/cds/AS ; export AS_ROOT
SEP_PATH=$RELEASE_PATH/cds/SEP ; export SEP_PATH
PATH=$AS_ROOT/scripts:$AS_ROOT/bin:$PATH ; export PATH
#
#echo "Compling started"
#( cd $AS_ROOT/src ; gmake all install )
#echo "Compiling done"
#echo "Installation done"
#
#



