#!/usr/bin/perl
#
###########################################################################
#
# This file is part of Celera Assembler, a software program that 
# assembles whole-genome shotgun reads into contigs and scaffolds.
# Copyright (C) 1999-2004, Applera Corporation. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received (LICENSE.txt) a copy of the GNU General Public 
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###########################################################################
#
#
#  Use this to launch multiple consensus partition jobs on queue
#  Requires 1) that the executable belocated in the working directory
#           2) all .cgb input be located in working directory
#           3) script is run from desired working directory
#              (a current working directory
#              call is made to assign a value to the working directory
#              for the batch jobs)
#
#  Usage:    submit_consensus prefix queue_name start_batch# end_batch#
#
#  Fine tune to suit, then uncomment the 'system($cmd)' line to
# actually run with the submits

#  Note: currently geard for cgb input with files with 001,002 style
# (as opposed to 1,2) to change, remove the '03' in all '%03d' below
#

# system("umask 2");
use Cwd;

$q = $ARGV[0]; # queue name
$prefix = $ARGV[1]; # the data set prefix
$s = $ARGV[2]; # starting partition
$e = $ARGV[3]; # ending parition

$prod = cwd();  # path to working directory

# $asbin = ".";  # path to executable
$asbin = $ENV{AS_BIN};
print "AS_BIN = $asbin\n";


if ( ! -e "$prod/batch_errfiles" ) {
  mkdir "$prod/batch_errfiles",0775;
}

for($i=$s; $i<=$e;$i=$i+1){
    print "Batch $i of unitigs\n";
      
  $subcmd = sprintf("cd %s; umask 2; ulimit -c 0 ; %s/consensus -P -S %d -m -U -z %s.frgStore_part %s_%03d.cgb",$prod,$asbin,$i,$prefix,$prefix,$i);
  print "$subcmd\n";
  
 $cmd = sprintf("bsub -q %s -P IR:HUM_ASM:H -J /Assembly/cns_%s_%03d -o %s/batch_errfiles/batch%03d.err -R \"rusage[physmem=1800]\" '%s'",$q,$prefix,$i,$prod,$i,$subcmd);

# $cmd = sprintf("batch <<EOB\n %s >& batch_errfiles/batch%03d.err \nEOB\n",$subcmd,$i);

 print "$cmd\n";
 system($cmd);
}
