#include <stdio.h>
#include <stdlib.h>
#include "fasta-accessor.H"

int
main(int argc, char **argv) {
  char *fwd =
    "CGCTTTAATGGGCGAACAGCCCAACCCTTGGGAGAGACTCCACCCCCAGGATGCGACGAGCCGACATCGAGGTGCCAAAC"
    "CATGCCGTCGATATGGACTCTGAGCGACGCCGCTTCCACAAGCCAGCGCCGGGTCACTAGTTCCGACTTTCGTCCCTGCT"
    "CGACCTGCCGGTCTCGCAGTCAAGCTCCCTTGTGCACTTAGCCTCCGTTACCTTTTAGGAGGCAACCGCCCCAGTTAAAC"
    "TACCCACCAGGCAATGTCCCTGATCCGGATCACGGACCTAGGTTAGATATCCAGAACGACGCTTCACAGTCTCCCACCTA"
    "TCCTACACAAGCCGTACCGAACACCAATACCAAGCTATAGTAAAGGTCCCGGGGTCTTTCCGTCCTGCTGCGCGTAACGA"
    "CAGTGGAGAAGTCGTTACGCCATTCGTGCAGGTCGGAACTTACCCGACAAGGAATTTCGCTACCTTAGGATGGTTATAGT"
    "TACCACCGCCGTTTACTGGGTTAACCTTCCAGCACCGGGCAGGCGTCAGTCCGTATACATCGTCTTGCGACTTAGCACGG"
    "ACCTGTGTTTTTAGTAAACAGTCGCTTCTCCCTGGTCTCTCCCCTTCTCCCGAAGTTACGGGGGTATTTTGCCGAGTTCC"
    "TTAACCATGATTCACTCGATCGCCTTGGTATTCTCTACCTAACCACCTGAGTCGGTTTGGTAGGATCACCCTGCTTCCCG"
    "CATTCGCGGTCACTATCAGGTCTCAGGATATGTGTGAGACGGATTTGCCTATCTCACTCCCTACACCCTTGGACGTGGAC"
    "TTGACTACTACCAAATCGGGTCACGCGCTCCGCTCAACATTCCATCACCCGAAGGTGACAGAAAAAAGAGTTTTAGGCGT"
    "TTAGCATCAAAAGGTTCATCTCGACTACGCCTGTCGGCCTCGCCTTAGGTCCCGACTTACCCAGGGCAGATTAGCTTGAC"
    "CCTGGAACCCTTGGTTATTCGGCGGACGGGTTTCTCGCCC";

  char *rev =
    "GGGCGAGAAACCCGTCCGCCGAATAACCAAGGGTTCCAGGGTCAAGCTAATCTGCCCTGGGTAAGTCGGGACCTAAGGCG"
    "AGGCCGACAGGCGTAGTCGAGATGAACCTTTTGATGCTAAACGCCTAAAACTCTTTTTTCTGTCACCTTCGGGTGATGGA"
    "ATGTTGAGCGGAGCGCGTGACCCGATTTGGTAGTAGTCAAGTCCACGTCCAAGGGTGTAGGGAGTGAGATAGGCAAATCC"
    "GTCTCACACATATCCTGAGACCTGATAGTGACCGCGAATGCGGGAAGCAGGGTGATCCTACCAAACCGACTCAGGTGGTT"
    "AGGTAGAGAATACCAAGGCGATCGAGTGAATCATGGTTAAGGAACTCGGCAAAATACCCCCGTAACTTCGGGAGAAGGGG"
    "AGAGACCAGGGAGAAGCGACTGTTTACTAAAAACACAGGTCCGTGCTAAGTCGCAAGACGATGTATACGGACTGACGCCT"
    "GCCCGGTGCTGGAAGGTTAACCCAGTAAACGGCGGTGGTAACTATAACCATCCTAAGGTAGCGAAATTCCTTGTCGGGTA"
    "AGTTCCGACCTGCACGAATGGCGTAACGACTTCTCCACTGTCGTTACGCGCAGCAGGACGGAAAGACCCCGGGACCTTTA"
    "CTATAGCTTGGTATTGGTGTTCGGTACGGCTTGTGTAGGATAGGTGGGAGACTGTGAAGCGTCGTTCTGGATATCTAACC"
    "TAGGTCCGTGATCCGGATCAGGGACATTGCCTGGTGGGTAGTTTAACTGGGGCGGTTGCCTCCTAAAAGGTAACGGAGGC"
    "TAAGTGCACAAGGGAGCTTGACTGCGAGACCGGCAGGTCGAGCAGGGACGAAAGTCGGAACTAGTGACCCGGCGCTGGCT"
    "TGTGGAAGCGGCGTCGCTCAGAGTCCATATCGACGGCATGGTTTGGCACCTCGATGTCGGCTCGTCGCATCCTGGGGGTG"
    "GAGTCTCTCCCAAGGGTTGGGCTGTTCGCCCATTAAAGCG";

  //
  //  Yup, real sequence.  I don't remember what it belongs to.
  //
  //  rev is the reverse complement of fwd, so if we make an accessor
  //  from it, and set the reverse-complement flag we should get back
  //  exactly fwd.
  //

  FastAAccessor F(fwd, 1000, false);
  FastAAccessor R(rev, 1000, true);
  u32bit        C;

  for (u32bit i=0; i<1000; i++)
    if (F[i] != R[i])
      exit(1);

  F.setPosition(0);
  R.setPosition(0);
  for (C=0; F.isValid() && R.isValid(); ++C, ++F, ++R)
    if (*F != *R)
      exit(2);
  if (C != 1000)
    exit(3);

  F.setPosition(1000);
  R.setPosition(1000);
  for (u32bit i=0; F.isValid() && R.isValid(); ++C, --F, --R)
    if (*F != *R)
      exit(4);
  if (C != 1000)
    exit(5);

  //
  //  XXX we still need to test pulling out a subsequence.  We're
  //  given coordinates in the forward direction, but want to pull out
  //  the reverse complement sequence.
  //
  char sub[1000];

  //  The forward sequence is:
  //
  //  100A 200N 100T 400N 200G
  //
  for (int i=0; i<1000; i++)
    sub[i] = 'N';
  for (int i=0; i<100; i++)
    sub[i] = 'A';
  for (int i=300; i<400; i++)
    sub[i] = 'T';
  for (int i=600; i<700; i++)
    sub[i] = 'R';
  for (int i=800; i<1000; i++)
    sub[i] = 'G';

  FastAAccessor S(sub, 1000, true);

  //  pull out the reverse-complement sequence from 300-400
  //

  //  Asking for sequence from 300 to 400 should give up exactly to
  //  'A' (reverse-complelent of T) block.
  //
  //  Without setting the range, we'd get back the sequence at
  //  700-600, the location when globally reverse-complemented.
  //
  S.setReverseComplementRange(300, 100);
  for (int i=300; i<400; i++)
    if (S[i] != 'A')
      fprintf(stderr, "got %c at pos %d\n", S[i], i), exit(5);

  S.setReverseComplementRange(0, 0);
  for (int i=300; i<400; i++)
    if (S[i] != 'Y')
      fprintf(stderr, "got %c at pos %d\n", S[i], i), exit(6);



  exit(0);
}

