#!/bin/sh

mv -i AS_global.c AS_global.C
mv -i AS_ALN/AS_ALN_bruteforcedp.c AS_ALN/AS_ALN_bruteforcedp.C
mv -i AS_ALN/AS_ALN_dpaligner.c AS_ALN/AS_ALN_dpaligner.C
mv -i AS_ALN/AS_ALN_forcns.c AS_ALN/AS_ALN_forcns.C
mv -i AS_ALN/AS_ALN_loverlapper.c AS_ALN/AS_ALN_loverlapper.C
mv -i AS_ALN/AS_ALN_pieceOlap.c AS_ALN/AS_ALN_pieceOlap.C
mv -i AS_ALN/AS_ALN_qvaligner.c AS_ALN/AS_ALN_qvaligner.C
mv -i AS_ALN/CA_ALN_local.c AS_ALN/CA_ALN_local.C
mv -i AS_ALN/CA_ALN_overlap.c AS_ALN/CA_ALN_overlap.C
mv -i AS_ALN/CA_ALN_scafcomp.c AS_ALN/CA_ALN_scafcomp.C
mv -i AS_BOG/fixUnitigs.c AS_BOG/fixUnitigs.C
mv -i AS_CGB/AS_CGB_Bubble.c AS_CGB/AS_CGB_Bubble.C
mv -i AS_CGB/AS_CGB_Bubble_Graph.c AS_CGB/AS_CGB_Bubble_Graph.C
mv -i AS_CGB/AS_CGB_Bubble_Popper.c AS_CGB/AS_CGB_Bubble_Popper.C
mv -i AS_CGB/AS_CGB_Bubble_PopperMethods.c AS_CGB/AS_CGB_Bubble_PopperMethods.C
mv -i AS_CGB/AS_CGB_Bubble_VertexSet.c AS_CGB/AS_CGB_Bubble_VertexSet.C
mv -i AS_CGB/AS_CGB_Bubble_dfs.c AS_CGB/AS_CGB_Bubble_dfs.C
mv -i AS_CGB/AS_CGB_cga.c AS_CGB/AS_CGB_cga.C
mv -i AS_CGB/AS_CGB_cgb.c AS_CGB/AS_CGB_cgb.C
mv -i AS_CGB/AS_CGB_chimeras.c AS_CGB/AS_CGB_chimeras.C
mv -i AS_CGB/AS_CGB_classify.c AS_CGB/AS_CGB_classify.C
mv -i AS_CGB/AS_CGB_edgemate.c AS_CGB/AS_CGB_edgemate.C
mv -i AS_CGB/AS_CGB_fga.c AS_CGB/AS_CGB_fga.C
mv -i AS_CGB/AS_CGB_fgb.c AS_CGB/AS_CGB_fgb.C
mv -i AS_CGB/AS_CGB_histo.c AS_CGB/AS_CGB_histo.C
mv -i AS_CGB/AS_CGB_main.c AS_CGB/AS_CGB_main.C
mv -i AS_CGB/AS_CGB_traversal.c AS_CGB/AS_CGB_traversal.C
mv -i AS_CGB/AS_CGB_unitigger.c AS_CGB/AS_CGB_unitigger.C
mv -i AS_CGB/AS_CGB_walk.c AS_CGB/AS_CGB_walk.C
mv -i AS_CGB/AS_FGB_contained.c AS_CGB/AS_FGB_contained.C
mv -i AS_CGB/AS_FGB_hanging_fragment.c AS_CGB/AS_FGB_hanging_fragment.C
mv -i AS_CGB/AS_FGB_io.c AS_CGB/AS_FGB_io.C
mv -i AS_CGB/AS_FGB_main.c AS_CGB/AS_FGB_main.C
mv -i AS_CGB/adjustAStat.c AS_CGB/adjustAStat.C
mv -i AS_CGW/AS_CGW_EdgeDiagnostics.c AS_CGW/AS_CGW_EdgeDiagnostics.C
mv -i AS_CGW/AS_CGW_dataTypes.c AS_CGW/AS_CGW_dataTypes.C
mv -i AS_CGW/AS_CGW_histo.c AS_CGW/AS_CGW_histo.C
mv -i AS_CGW/AS_CGW_main.c AS_CGW/AS_CGW_main.C
mv -i AS_CGW/CIEdgeT_CGW.c AS_CGW/CIEdgeT_CGW.C
mv -i AS_CGW/CIScaffoldT_Biconnected_CGW.c AS_CGW/CIScaffoldT_Biconnected_CGW.C
mv -i AS_CGW/CIScaffoldT_CGW.c AS_CGW/CIScaffoldT_CGW.C
mv -i AS_CGW/CIScaffoldT_Cleanup_CGW.c AS_CGW/CIScaffoldT_Cleanup_CGW.C
mv -i AS_CGW/CIScaffoldT_Merge_CGW.c AS_CGW/CIScaffoldT_Merge_CGW.C
mv -i AS_CGW/Celamy_CGW.c AS_CGW/Celamy_CGW.C
mv -i AS_CGW/ChunkOverlap_CGW.c AS_CGW/ChunkOverlap_CGW.C
mv -i AS_CGW/ContigT_CGW.c AS_CGW/ContigT_CGW.C
mv -i AS_CGW/DemoteUnitigsWithRBP_CGW.c AS_CGW/DemoteUnitigsWithRBP_CGW.C
mv -i AS_CGW/GraphCGW_T.c AS_CGW/GraphCGW_T.C
mv -i AS_CGW/Input_CGW.c AS_CGW/Input_CGW.C
mv -i AS_CGW/Instrument_CGW.c AS_CGW/Instrument_CGW.C
mv -i AS_CGW/InterleavedMerging.c AS_CGW/InterleavedMerging.C
mv -i AS_CGW/LeastSquaresGaps_CGW.c AS_CGW/LeastSquaresGaps_CGW.C
mv -i AS_CGW/MergeEdges_CGW.c AS_CGW/MergeEdges_CGW.C
mv -i AS_CGW/Output_CGW.c AS_CGW/Output_CGW.C
mv -i AS_CGW/SEdgeT_CGW.c AS_CGW/SEdgeT_CGW.C
mv -i AS_CGW/ScaffoldGraph_CGW.c AS_CGW/ScaffoldGraph_CGW.C
mv -i AS_CGW/SplitChunks_CGW.c AS_CGW/SplitChunks_CGW.C
mv -i AS_CGW/SplitScaffolds_CGW.c AS_CGW/SplitScaffolds_CGW.C
mv -i AS_CGW/Stats_CGW.c AS_CGW/Stats_CGW.C
mv -i AS_CGW/TransitiveReduction_CGW.c AS_CGW/TransitiveReduction_CGW.C
mv -i AS_CGW/createFrgDeletes.c AS_CGW/createFrgDeletes.C
mv -i AS_CGW/dumpCloneMiddles.c AS_CGW/dumpCloneMiddles.C
mv -i AS_CGW/dumpSingletons.c AS_CGW/dumpSingletons.C
mv -i AS_CGW/eCR-diagnostic.c AS_CGW/eCR-diagnostic.C
mv -i AS_CGW/eCR-examineGap.c AS_CGW/eCR-examineGap.C
mv -i AS_CGW/eCR.c AS_CGW/eCR.C
mv -i AS_CGW/exploreGapStructure.c AS_CGW/exploreGapStructure.C
mv -i AS_CGW/fragmentPlacement.c AS_CGW/fragmentPlacement.C
mv -i AS_CGW/frgs2clones.c AS_CGW/frgs2clones.C
mv -i AS_CGW/resolveSurrogates.c AS_CGW/resolveSurrogates.C
mv -i AS_CNS/AS_CNS_asmReBaseCall.c AS_CNS/AS_CNS_asmReBaseCall.C
mv -i AS_CNS/AbacusRefine.c AS_CNS/AbacusRefine.C
mv -i AS_CNS/ApplyAlignment.c AS_CNS/ApplyAlignment.C
mv -i AS_CNS/Array_CNS.c AS_CNS/Array_CNS.C
mv -i AS_CNS/BaseCall.c AS_CNS/BaseCall.C
mv -i AS_CNS/Consensus_CNS.c AS_CNS/Consensus_CNS.C
mv -i AS_CNS/GetAlignmentTrace.c AS_CNS/GetAlignmentTrace.C
mv -i AS_CNS/MergeMultiAligns.c AS_CNS/MergeMultiAligns.C
mv -i AS_CNS/MergeRefine.c AS_CNS/MergeRefine.C
mv -i AS_CNS/MultiAlign.c AS_CNS/MultiAlign.C
mv -i AS_CNS/MultiAlignContig.c AS_CNS/MultiAlignContig.C
mv -i AS_CNS/MultiAlignFromICM.c AS_CNS/MultiAlignFromICM.C
mv -i AS_CNS/MultiAlignFromIUM.c AS_CNS/MultiAlignFromIUM.C
mv -i AS_CNS/MultiAlignPrint.c AS_CNS/MultiAlignPrint.C
mv -i AS_CNS/MultiAlignStore_CNS.c AS_CNS/MultiAlignStore_CNS.C
mv -i AS_CNS/MultiAlignUnitig.c AS_CNS/MultiAlignUnitig.C
mv -i AS_CNS/MultiAlignment_CNS.c AS_CNS/MultiAlignment_CNS.C
mv -i AS_CNS/PrintAlignment.c AS_CNS/PrintAlignment.C
mv -i AS_CNS/RefreshMANode.c AS_CNS/RefreshMANode.C
mv -i AS_CNS/ReplaceEndUnitigInContig.c AS_CNS/ReplaceEndUnitigInContig.C
mv -i AS_CNS/SeqAn_CNS.c AS_CNS/SeqAn_CNS.C
mv -i AS_ENV/chimChe.c AS_ENV/chimChe.C
mv -i AS_ENV/greedyFragmentTiling.c AS_ENV/greedyFragmentTiling.C
mv -i AS_ENV/metagenomics_ovl_analyses.c AS_ENV/metagenomics_ovl_analyses.C
mv -i AS_GKP/AS_GKP_bench.c AS_GKP/AS_GKP_bench.C
mv -i AS_GKP/AS_GKP_buildPartition.c AS_GKP/AS_GKP_buildPartition.C
mv -i AS_GKP/AS_GKP_checkBatch.c AS_GKP/AS_GKP_checkBatch.C
mv -i AS_GKP/AS_GKP_checkFrag.c AS_GKP/AS_GKP_checkFrag.C
mv -i AS_GKP/AS_GKP_checkLibrary.c AS_GKP/AS_GKP_checkLibrary.C
mv -i AS_GKP/AS_GKP_checkLink.c AS_GKP/AS_GKP_checkLink.C
mv -i AS_GKP/AS_GKP_dump.c AS_GKP/AS_GKP_dump.C
mv -i AS_GKP/AS_GKP_edit.c AS_GKP/AS_GKP_edit.C
mv -i AS_GKP/AS_GKP_errors.c AS_GKP/AS_GKP_errors.C
mv -i AS_GKP/AS_GKP_main.c AS_GKP/AS_GKP_main.C
mv -i AS_GKP/AS_GKP_rearrange.c AS_GKP/AS_GKP_rearrange.C
mv -i AS_GKP/AS_GKP_rebuildMap.c AS_GKP/AS_GKP_rebuildMap.C
mv -i AS_GKP/sffToCA.c AS_GKP/sffToCA.C
mv -i AS_MSG/AS_MSG_pmesg.c AS_MSG/AS_MSG_pmesg.C
mv -i AS_MSG/AS_MSG_pmesg1.c AS_MSG/AS_MSG_pmesg1.C
mv -i AS_MSG/AS_MSG_pmesg2.c AS_MSG/AS_MSG_pmesg2.C
mv -i AS_MSG/ExtractMessages.c AS_MSG/ExtractMessages.C
mv -i AS_MSG/remove_fragment.c AS_MSG/remove_fragment.C
mv -i AS_OBT/AS_OBT_acceptableOverlap.c AS_OBT/AS_OBT_acceptableOverlap.C
mv -i AS_OBT/getNumScaffolds.c AS_OBT/getNumScaffolds.C
mv -i AS_OVL/AS_OVL_delcher.c AS_OVL/AS_OVL_delcher.C
mv -i AS_OVL/AS_OVL_driver.c AS_OVL/AS_OVL_driver.C
mv -i AS_OVL/AS_OVL_driver_ca.c AS_OVL/AS_OVL_driver_ca.C
mv -i AS_OVL/AS_OVL_overlap.c AS_OVL/AS_OVL_overlap.C
mv -i AS_OVL/AS_OVL_overlap_ca.c AS_OVL/AS_OVL_overlap_ca.C
mv -i AS_OVL/CatCorrectsOVL.c AS_OVL/CatCorrectsOVL.C
mv -i AS_OVL/CatEratesOVL.c AS_OVL/CatEratesOVL.C
mv -i AS_OVL/CorrectOlapsOVL.c AS_OVL/CorrectOlapsOVL.C
mv -i AS_OVL/FragCorrectOVL.c AS_OVL/FragCorrectOVL.C
mv -i AS_OVL/OlapFromSeedsOVL.c AS_OVL/OlapFromSeedsOVL.C
mv -i AS_OVL/SharedOVL.c AS_OVL/SharedOVL.C
mv -i AS_OVL/ShowCorrectsOVL.c AS_OVL/ShowCorrectsOVL.C
mv -i AS_OVS/AS_OVS_overlap.c AS_OVS/AS_OVS_overlap.C
mv -i AS_OVS/AS_OVS_overlapFile.c AS_OVS/AS_OVS_overlapFile.C
mv -i AS_OVS/AS_OVS_overlapStats.c AS_OVS/AS_OVS_overlapStats.C
mv -i AS_OVS/AS_OVS_overlapStore.c AS_OVS/AS_OVS_overlapStore.C
mv -i AS_OVS/convertOverlap.c AS_OVS/convertOverlap.C
mv -i AS_OVS/filterOverlap.c AS_OVS/filterOverlap.C
mv -i AS_OVS/overlapStats.c AS_OVS/overlapStats.C
mv -i AS_OVS/overlapStore.c AS_OVS/overlapStore.C
mv -i AS_OVS/overlapStore_build.c AS_OVS/overlapStore_build.C
mv -i AS_OVS/overlapStore_dump.c AS_OVS/overlapStore_dump.C
mv -i AS_OVS/overlapStore_erates.c AS_OVS/overlapStore_erates.C
mv -i AS_OVS/overlapStore_merge.c AS_OVS/overlapStore_merge.C
mv -i AS_OVS/overlapStore_stats.c AS_OVS/overlapStore_stats.C

mv -i AS_PER/AS_PER_asmStore.c AS_PER/AS_PER_asmStore.C
mv -i AS_PER/AS_PER_encodeSequenceQuality.c AS_PER/AS_PER_encodeSequenceQuality.C
mv -i AS_PER/AS_PER_genericStore.c AS_PER/AS_PER_genericStore.C

mv -i AS_REZ/ConsistencyChecksREZ.c AS_REZ/ConsistencyChecksREZ.C
mv -i AS_REZ/GapFillREZ.c AS_REZ/GapFillREZ.C
mv -i AS_REZ/GapWalkerREZ.c AS_REZ/GapWalkerREZ.C
mv -i AS_REZ/MicroHetIUM.c AS_REZ/MicroHetIUM.C
mv -i AS_REZ/MicroHetREZ.c AS_REZ/MicroHetREZ.C
mv -i AS_REZ/StatisticsREZ.c AS_REZ/StatisticsREZ.C
mv -i AS_REZ/UpdateREZ.c AS_REZ/UpdateREZ.C
mv -i AS_REZ/UtilsREZ.c AS_REZ/UtilsREZ.C
mv -i AS_RUN/fragmentDepth.c AS_RUN/fragmentDepth.C
mv -i AS_RUN/markUniqueUnique.c AS_RUN/markUniqueUnique.C
mv -i AS_SDB/AS_SDB_SequenceDB.c AS_SDB/AS_SDB_SequenceDB.C
mv -i AS_SDB/PartitionSDB.c AS_SDB/PartitionSDB.C
mv -i AS_TER/AS_TER_terminator.c AS_TER/AS_TER_terminator.C
mv -i AS_TER/asmOutputFasta.c AS_TER/asmOutputFasta.C
mv -i AS_TER/buildPosMap.c AS_TER/buildPosMap.C
mv -i AS_TER/fragsInVars.c AS_TER/fragsInVars.C
mv -i AS_UID/SYS_UIDclient.c AS_UID/SYS_UIDclient.C
mv -i AS_UID/SYS_UIDclient_JTC.c AS_UID/SYS_UIDclient_JTC.C
mv -i AS_UID/SYS_UIDclient_LOCAL.c AS_UID/SYS_UIDclient_LOCAL.C
mv -i AS_UID/SYS_UIDcommon.c AS_UID/SYS_UIDcommon.C
mv -i AS_UID/SYS_UIDerror.c AS_UID/SYS_UIDerror.C
mv -i AS_UID/uidclient.c AS_UID/uidclient.C
mv -i AS_UID/uidsrvd.c AS_UID/uidsrvd.C
mv -i AS_UTL/AS_UTL_GPL.c AS_UTL/AS_UTL_GPL.C
mv -i AS_UTL/AS_UTL_Hash.c AS_UTL/AS_UTL_Hash.C
mv -i AS_UTL/AS_UTL_UID.c AS_UTL/AS_UTL_UID.C
mv -i AS_UTL/AS_UTL_Var.c AS_UTL/AS_UTL_Var.C
mv -i AS_UTL/AS_UTL_alloc.c AS_UTL/AS_UTL_alloc.C
mv -i AS_UTL/AS_UTL_fasta.c AS_UTL/AS_UTL_fasta.C
mv -i AS_UTL/AS_UTL_fileIO.c AS_UTL/AS_UTL_fileIO.C
mv -i AS_UTL/AS_UTL_heap.c AS_UTL/AS_UTL_heap.C
mv -i AS_UTL/AS_UTL_histo.c AS_UTL/AS_UTL_histo.C
mv -i AS_UTL/AS_UTL_interval.c AS_UTL/AS_UTL_interval.C
mv -i AS_UTL/AS_UTL_param_proc.c AS_UTL/AS_UTL_param_proc.C
mv -i AS_UTL/AS_UTL_qsort_mt.c AS_UTL/AS_UTL_qsort_mt.C
mv -i AS_UTL/AS_UTL_rand.c AS_UTL/AS_UTL_rand.C
mv -i AS_UTL/AS_UTL_reverseComplement.c AS_UTL/AS_UTL_reverseComplement.C
mv -i AS_UTL/AS_UTL_skiplist.c AS_UTL/AS_UTL_skiplist.C
mv -i AS_UTL/AS_UTL_skiplist_test.c AS_UTL/AS_UTL_skiplist_test.C
mv -i AS_UTL/AS_UTL_testhisto.c AS_UTL/AS_UTL_testhisto.C
mv -i AS_UTL/UnionFind_AS.c AS_UTL/UnionFind_AS.C
mv -i AS_UTL/testHashTable.c AS_UTL/testHashTable.C
mv -i AS_UTL/testRand.c AS_UTL/testRand.C
mv -i AS_UTL/testVar.c AS_UTL/testVar.C
