#!/bin/sh

mv -i AS_global.C AS_global.c
mv -i AS_ALN/AS_ALN_bruteforcedp.C AS_ALN/AS_ALN_bruteforcedp.c
mv -i AS_ALN/AS_ALN_dpaligner.C AS_ALN/AS_ALN_dpaligner.c
mv -i AS_ALN/AS_ALN_forcns.C AS_ALN/AS_ALN_forcns.c
mv -i AS_ALN/AS_ALN_loverlapper.C AS_ALN/AS_ALN_loverlapper.c
mv -i AS_ALN/AS_ALN_pieceOlap.C AS_ALN/AS_ALN_pieceOlap.c
mv -i AS_ALN/AS_ALN_qvaligner.C AS_ALN/AS_ALN_qvaligner.c
mv -i AS_ALN/CA_ALN_local.C AS_ALN/CA_ALN_local.c
mv -i AS_ALN/CA_ALN_overlap.C AS_ALN/CA_ALN_overlap.c
mv -i AS_ALN/CA_ALN_scafcomp.C AS_ALN/CA_ALN_scafcomp.c
mv -i AS_BOG/fixUnitigs.C AS_BOG/fixUnitigs.c
mv -i AS_CGB/AS_CGB_Bubble.C AS_CGB/AS_CGB_Bubble.c
mv -i AS_CGB/AS_CGB_Bubble_Graph.C AS_CGB/AS_CGB_Bubble_Graph.c
mv -i AS_CGB/AS_CGB_Bubble_Popper.C AS_CGB/AS_CGB_Bubble_Popper.c
mv -i AS_CGB/AS_CGB_Bubble_PopperMethods.C AS_CGB/AS_CGB_Bubble_PopperMethods.c
mv -i AS_CGB/AS_CGB_Bubble_VertexSet.C AS_CGB/AS_CGB_Bubble_VertexSet.c
mv -i AS_CGB/AS_CGB_Bubble_dfs.C AS_CGB/AS_CGB_Bubble_dfs.c
mv -i AS_CGB/AS_CGB_cga.C AS_CGB/AS_CGB_cga.c
mv -i AS_CGB/AS_CGB_cgb.C AS_CGB/AS_CGB_cgb.c
mv -i AS_CGB/AS_CGB_chimeras.C AS_CGB/AS_CGB_chimeras.c
mv -i AS_CGB/AS_CGB_classify.C AS_CGB/AS_CGB_classify.c
mv -i AS_CGB/AS_CGB_edgemate.C AS_CGB/AS_CGB_edgemate.c
mv -i AS_CGB/AS_CGB_fga.C AS_CGB/AS_CGB_fga.c
mv -i AS_CGB/AS_CGB_fgb.C AS_CGB/AS_CGB_fgb.c
mv -i AS_CGB/AS_CGB_histo.C AS_CGB/AS_CGB_histo.c
mv -i AS_CGB/AS_CGB_main.C AS_CGB/AS_CGB_main.c
mv -i AS_CGB/AS_CGB_traversal.C AS_CGB/AS_CGB_traversal.c
mv -i AS_CGB/AS_CGB_unitigger.C AS_CGB/AS_CGB_unitigger.c
mv -i AS_CGB/AS_CGB_walk.C AS_CGB/AS_CGB_walk.c
mv -i AS_CGB/AS_FGB_contained.C AS_CGB/AS_FGB_contained.c
mv -i AS_CGB/AS_FGB_hanging_fragment.C AS_CGB/AS_FGB_hanging_fragment.c
mv -i AS_CGB/AS_FGB_io.C AS_CGB/AS_FGB_io.c
mv -i AS_CGB/AS_FGB_main.C AS_CGB/AS_FGB_main.c
mv -i AS_CGB/adjustAStat.C AS_CGB/adjustAStat.c
mv -i AS_CGW/AS_CGW_EdgeDiagnostics.C AS_CGW/AS_CGW_EdgeDiagnostics.c
mv -i AS_CGW/AS_CGW_dataTypes.C AS_CGW/AS_CGW_dataTypes.c
mv -i AS_CGW/AS_CGW_histo.C AS_CGW/AS_CGW_histo.c
mv -i AS_CGW/AS_CGW_main.C AS_CGW/AS_CGW_main.c
mv -i AS_CGW/CIEdgeT_CGW.C AS_CGW/CIEdgeT_CGW.c
mv -i AS_CGW/CIScaffoldT_Biconnected_CGW.C AS_CGW/CIScaffoldT_Biconnected_CGW.c
mv -i AS_CGW/CIScaffoldT_CGW.C AS_CGW/CIScaffoldT_CGW.c
mv -i AS_CGW/CIScaffoldT_Cleanup_CGW.C AS_CGW/CIScaffoldT_Cleanup_CGW.c
mv -i AS_CGW/CIScaffoldT_Merge_CGW.C AS_CGW/CIScaffoldT_Merge_CGW.c
mv -i AS_CGW/Celamy_CGW.C AS_CGW/Celamy_CGW.c
mv -i AS_CGW/ChunkOverlap_CGW.C AS_CGW/ChunkOverlap_CGW.c
mv -i AS_CGW/ContigT_CGW.C AS_CGW/ContigT_CGW.c
mv -i AS_CGW/DemoteUnitigsWithRBP_CGW.C AS_CGW/DemoteUnitigsWithRBP_CGW.c
mv -i AS_CGW/GraphCGW_T.C AS_CGW/GraphCGW_T.c
mv -i AS_CGW/Input_CGW.C AS_CGW/Input_CGW.c
mv -i AS_CGW/Instrument_CGW.C AS_CGW/Instrument_CGW.c
mv -i AS_CGW/InterleavedMerging.C AS_CGW/InterleavedMerging.c
mv -i AS_CGW/LeastSquaresGaps_CGW.C AS_CGW/LeastSquaresGaps_CGW.c
mv -i AS_CGW/MergeEdges_CGW.C AS_CGW/MergeEdges_CGW.c
mv -i AS_CGW/Output_CGW.C AS_CGW/Output_CGW.c
mv -i AS_CGW/SEdgeT_CGW.C AS_CGW/SEdgeT_CGW.c
mv -i AS_CGW/ScaffoldGraph_CGW.C AS_CGW/ScaffoldGraph_CGW.c
mv -i AS_CGW/SplitChunks_CGW.C AS_CGW/SplitChunks_CGW.c
mv -i AS_CGW/SplitScaffolds_CGW.C AS_CGW/SplitScaffolds_CGW.c
mv -i AS_CGW/Stats_CGW.C AS_CGW/Stats_CGW.c
mv -i AS_CGW/TransitiveReduction_CGW.C AS_CGW/TransitiveReduction_CGW.c
mv -i AS_CGW/createFrgDeletes.C AS_CGW/createFrgDeletes.c
mv -i AS_CGW/dumpCloneMiddles.C AS_CGW/dumpCloneMiddles.c
mv -i AS_CGW/dumpSingletons.C AS_CGW/dumpSingletons.c
mv -i AS_CGW/eCR-diagnostic.C AS_CGW/eCR-diagnostic.c
mv -i AS_CGW/eCR-examineGap.C AS_CGW/eCR-examineGap.c
mv -i AS_CGW/eCR.C AS_CGW/eCR.c
mv -i AS_CGW/exploreGapStructure.C AS_CGW/exploreGapStructure.c
mv -i AS_CGW/fragmentPlacement.C AS_CGW/fragmentPlacement.c
mv -i AS_CGW/frgs2clones.C AS_CGW/frgs2clones.c
mv -i AS_CGW/resolveSurrogates.C AS_CGW/resolveSurrogates.c
mv -i AS_CNS/AS_CNS_asmReBaseCall.C AS_CNS/AS_CNS_asmReBaseCall.c
mv -i AS_CNS/AbacusRefine.C AS_CNS/AbacusRefine.c
mv -i AS_CNS/ApplyAlignment.C AS_CNS/ApplyAlignment.c
mv -i AS_CNS/Array_CNS.C AS_CNS/Array_CNS.c
mv -i AS_CNS/BaseCall.C AS_CNS/BaseCall.c
mv -i AS_CNS/Consensus_CNS.C AS_CNS/Consensus_CNS.c
mv -i AS_CNS/GetAlignmentTrace.C AS_CNS/GetAlignmentTrace.c
mv -i AS_CNS/MergeMultiAligns.C AS_CNS/MergeMultiAligns.c
mv -i AS_CNS/MergeRefine.C AS_CNS/MergeRefine.c
mv -i AS_CNS/MultiAlign.C AS_CNS/MultiAlign.c
mv -i AS_CNS/MultiAlignContig.C AS_CNS/MultiAlignContig.c
mv -i AS_CNS/MultiAlignFromICM.C AS_CNS/MultiAlignFromICM.c
mv -i AS_CNS/MultiAlignFromIUM.C AS_CNS/MultiAlignFromIUM.c
mv -i AS_CNS/MultiAlignPrint.C AS_CNS/MultiAlignPrint.c
mv -i AS_CNS/MultiAlignStore_CNS.C AS_CNS/MultiAlignStore_CNS.c
mv -i AS_CNS/MultiAlignUnitig.C AS_CNS/MultiAlignUnitig.c
mv -i AS_CNS/MultiAlignment_CNS.C AS_CNS/MultiAlignment_CNS.c
mv -i AS_CNS/PrintAlignment.C AS_CNS/PrintAlignment.c
mv -i AS_CNS/RefreshMANode.C AS_CNS/RefreshMANode.c
mv -i AS_CNS/ReplaceEndUnitigInContig.C AS_CNS/ReplaceEndUnitigInContig.c
mv -i AS_CNS/SeqAn_CNS.C AS_CNS/SeqAn_CNS.c
mv -i AS_ENV/chimChe.C AS_ENV/chimChe.c
mv -i AS_ENV/greedyFragmentTiling.C AS_ENV/greedyFragmentTiling.c
mv -i AS_ENV/metagenomics_ovl_analyses.C AS_ENV/metagenomics_ovl_analyses.c
mv -i AS_GKP/AS_GKP_bench.C AS_GKP/AS_GKP_bench.c
mv -i AS_GKP/AS_GKP_buildPartition.C AS_GKP/AS_GKP_buildPartition.c
mv -i AS_GKP/AS_GKP_checkBatch.C AS_GKP/AS_GKP_checkBatch.c
mv -i AS_GKP/AS_GKP_checkFrag.C AS_GKP/AS_GKP_checkFrag.c
mv -i AS_GKP/AS_GKP_checkLibrary.C AS_GKP/AS_GKP_checkLibrary.c
mv -i AS_GKP/AS_GKP_checkLink.C AS_GKP/AS_GKP_checkLink.c
mv -i AS_GKP/AS_GKP_dump.C AS_GKP/AS_GKP_dump.c
mv -i AS_GKP/AS_GKP_edit.C AS_GKP/AS_GKP_edit.c
mv -i AS_GKP/AS_GKP_errors.C AS_GKP/AS_GKP_errors.c
mv -i AS_GKP/AS_GKP_main.C AS_GKP/AS_GKP_main.c
mv -i AS_GKP/AS_GKP_rearrange.C AS_GKP/AS_GKP_rearrange.c
mv -i AS_GKP/AS_GKP_rebuildMap.C AS_GKP/AS_GKP_rebuildMap.c
mv -i AS_GKP/sffToCA.C AS_GKP/sffToCA.c
mv -i AS_MSG/AS_MSG_pmesg.C AS_MSG/AS_MSG_pmesg.c
mv -i AS_MSG/AS_MSG_pmesg1.C AS_MSG/AS_MSG_pmesg1.c
mv -i AS_MSG/AS_MSG_pmesg2.C AS_MSG/AS_MSG_pmesg2.c
mv -i AS_MSG/ExtractMessages.C AS_MSG/ExtractMessages.c
mv -i AS_MSG/remove_fragment.C AS_MSG/remove_fragment.c
mv -i AS_OBT/AS_OBT_acceptableOverlap.C AS_OBT/AS_OBT_acceptableOverlap.c
mv -i AS_OBT/getNumScaffolds.C AS_OBT/getNumScaffolds.c
mv -i AS_OVL/AS_OVL_delcher.C AS_OVL/AS_OVL_delcher.c
mv -i AS_OVL/AS_OVL_driver.C AS_OVL/AS_OVL_driver.c
mv -i AS_OVL/AS_OVL_driver_ca.C AS_OVL/AS_OVL_driver_ca.c
mv -i AS_OVL/AS_OVL_overlap.C AS_OVL/AS_OVL_overlap.c
mv -i AS_OVL/AS_OVL_overlap_ca.C AS_OVL/AS_OVL_overlap_ca.c
mv -i AS_OVL/CatCorrectsOVL.C AS_OVL/CatCorrectsOVL.c
mv -i AS_OVL/CatEratesOVL.C AS_OVL/CatEratesOVL.c
mv -i AS_OVL/CorrectOlapsOVL.C AS_OVL/CorrectOlapsOVL.c
mv -i AS_OVL/FragCorrectOVL.C AS_OVL/FragCorrectOVL.c
mv -i AS_OVL/OlapFromSeedsOVL.C AS_OVL/OlapFromSeedsOVL.c
mv -i AS_OVL/SharedOVL.C AS_OVL/SharedOVL.c
mv -i AS_OVL/ShowCorrectsOVL.C AS_OVL/ShowCorrectsOVL.c
mv -i AS_OVS/AS_OVS_overlap.C AS_OVS/AS_OVS_overlap.c
mv -i AS_OVS/AS_OVS_overlapFile.C AS_OVS/AS_OVS_overlapFile.c
mv -i AS_OVS/AS_OVS_overlapStats.C AS_OVS/AS_OVS_overlapStats.c
mv -i AS_OVS/AS_OVS_overlapStore.C AS_OVS/AS_OVS_overlapStore.c
mv -i AS_OVS/convertOverlap.C AS_OVS/convertOverlap.c
mv -i AS_OVS/filterOverlap.C AS_OVS/filterOverlap.c
mv -i AS_OVS/overlapStats.C AS_OVS/overlapStats.c
mv -i AS_OVS/overlapStore.C AS_OVS/overlapStore.c
mv -i AS_OVS/overlapStore_build.C AS_OVS/overlapStore_build.c
mv -i AS_OVS/overlapStore_dump.C AS_OVS/overlapStore_dump.c
mv -i AS_OVS/overlapStore_erates.C AS_OVS/overlapStore_erates.c
mv -i AS_OVS/overlapStore_merge.C AS_OVS/overlapStore_merge.c
mv -i AS_OVS/overlapStore_stats.C AS_OVS/overlapStore_stats.c

mv -i AS_PER/AS_PER_asmStore.C AS_PER/AS_PER_asmStore.c
mv -i AS_PER/AS_PER_encodeSequenceQuality.C AS_PER/AS_PER_encodeSequenceQuality.c
mv -i AS_PER/AS_PER_genericStore.C AS_PER/AS_PER_genericStore.c

mv -i AS_REZ/ConsistencyChecksREZ.C AS_REZ/ConsistencyChecksREZ.c
mv -i AS_REZ/GapFillREZ.C AS_REZ/GapFillREZ.c
mv -i AS_REZ/GapWalkerREZ.C AS_REZ/GapWalkerREZ.c
mv -i AS_REZ/MicroHetIUM.C AS_REZ/MicroHetIUM.c
mv -i AS_REZ/MicroHetREZ.C AS_REZ/MicroHetREZ.c
mv -i AS_REZ/StatisticsREZ.C AS_REZ/StatisticsREZ.c
mv -i AS_REZ/UpdateREZ.C AS_REZ/UpdateREZ.c
mv -i AS_REZ/UtilsREZ.C AS_REZ/UtilsREZ.c
mv -i AS_RUN/fragmentDepth.C AS_RUN/fragmentDepth.c
mv -i AS_RUN/markUniqueUnique.C AS_RUN/markUniqueUnique.c
mv -i AS_SDB/AS_SDB_SequenceDB.C AS_SDB/AS_SDB_SequenceDB.c
mv -i AS_SDB/PartitionSDB.C AS_SDB/PartitionSDB.c
mv -i AS_TER/AS_TER_terminator.C AS_TER/AS_TER_terminator.c
mv -i AS_TER/asmOutputFasta.C AS_TER/asmOutputFasta.c
mv -i AS_TER/buildPosMap.C AS_TER/buildPosMap.c
mv -i AS_TER/fragsInVars.C AS_TER/fragsInVars.c
mv -i AS_UID/SYS_UIDclient.C AS_UID/SYS_UIDclient.c
mv -i AS_UID/SYS_UIDclient_JTC.C AS_UID/SYS_UIDclient_JTC.c
mv -i AS_UID/SYS_UIDclient_LOCAL.C AS_UID/SYS_UIDclient_LOCAL.c
mv -i AS_UID/SYS_UIDcommon.C AS_UID/SYS_UIDcommon.c
mv -i AS_UID/SYS_UIDerror.C AS_UID/SYS_UIDerror.c
mv -i AS_UID/uidclient.C AS_UID/uidclient.c
mv -i AS_UID/uidsrvd.C AS_UID/uidsrvd.c
mv -i AS_UTL/AS_UTL_GPL.C AS_UTL/AS_UTL_GPL.c
mv -i AS_UTL/AS_UTL_Hash.C AS_UTL/AS_UTL_Hash.c
mv -i AS_UTL/AS_UTL_UID.C AS_UTL/AS_UTL_UID.c
mv -i AS_UTL/AS_UTL_Var.C AS_UTL/AS_UTL_Var.c
mv -i AS_UTL/AS_UTL_alloc.C AS_UTL/AS_UTL_alloc.c
mv -i AS_UTL/AS_UTL_fasta.C AS_UTL/AS_UTL_fasta.c
mv -i AS_UTL/AS_UTL_fileIO.C AS_UTL/AS_UTL_fileIO.c
mv -i AS_UTL/AS_UTL_heap.C AS_UTL/AS_UTL_heap.c
mv -i AS_UTL/AS_UTL_histo.C AS_UTL/AS_UTL_histo.c
mv -i AS_UTL/AS_UTL_interval.C AS_UTL/AS_UTL_interval.c
mv -i AS_UTL/AS_UTL_param_proc.C AS_UTL/AS_UTL_param_proc.c
mv -i AS_UTL/AS_UTL_qsort_mt.C AS_UTL/AS_UTL_qsort_mt.c
mv -i AS_UTL/AS_UTL_rand.C AS_UTL/AS_UTL_rand.c
mv -i AS_UTL/AS_UTL_reverseComplement.C AS_UTL/AS_UTL_reverseComplement.c
mv -i AS_UTL/AS_UTL_skiplist.C AS_UTL/AS_UTL_skiplist.c
mv -i AS_UTL/AS_UTL_skiplist_test.C AS_UTL/AS_UTL_skiplist_test.c
mv -i AS_UTL/AS_UTL_testhisto.C AS_UTL/AS_UTL_testhisto.c
mv -i AS_UTL/UnionFind_AS.C AS_UTL/UnionFind_AS.c
mv -i AS_UTL/testHashTable.C AS_UTL/testHashTable.c
mv -i AS_UTL/testRand.C AS_UTL/testRand.c
mv -i AS_UTL/testVar.C AS_UTL/testVar.c
