
/**************************************************************************
 * This file is part of Celera Assembler, a software program that 
 * assembles whole-genome shotgun reads into contigs and scaffolds.
 * Copyright (C) 1999-2004, Applera Corporation. All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received (LICENSE.txt) a copy of the GNU General Public 
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *************************************************************************/

/* euidClient.c
   Generated by gSOAP 2.3 rev 2 from EUIDServer.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#include "euidH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_BEGIN_NAMESPACE(euid)

SOAP_SOURCE_STAMP("@(#) euidClient.c ver 2.3 rev 2 2003-08-05 20:40:36 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_impl__ping(struct soap *soap, const char *URL, const char *action, struct impl__pingResponse *out)
{
	struct impl__ping soap_tmp_impl__ping;
	if (!URL)
		URL = "http://tools:8190/axis/services/EUIDServer";
	if (!action)
		action = "";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_impl__ping(soap, &soap_tmp_impl__ping);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_impl__ping(soap, &soap_tmp_impl__ping, "impl:ping", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	}
	if (soap_connect(soap, URL, action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impl__ping(soap, &soap_tmp_impl__ping, "impl:ping", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_impl__pingResponse(soap, out);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_impl__pingResponse(soap, out, "impl:pingResponse", "impl:pingResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_impl__getEUIDNamespaces(struct soap *soap, const char *URL, const char *action, struct impl__getEUIDNamespacesResponse *out)
{
	struct impl__getEUIDNamespaces soap_tmp_impl__getEUIDNamespaces;
	if (!URL)
		URL = "http://tools:8190/axis/services/EUIDServer";
	if (!action)
		action = "";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_impl__getEUIDNamespaces(soap, &soap_tmp_impl__getEUIDNamespaces);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_impl__getEUIDNamespaces(soap, &soap_tmp_impl__getEUIDNamespaces, "impl:getEUIDNamespaces", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	}
	if (soap_connect(soap, URL, action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impl__getEUIDNamespaces(soap, &soap_tmp_impl__getEUIDNamespaces, "impl:getEUIDNamespaces", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_impl__getEUIDNamespacesResponse(soap, out);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_impl__getEUIDNamespacesResponse(soap, out, "impl:getEUIDNamespacesResponse", "impl:getEUIDNamespacesResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_impl__getEUIDBlock(struct soap *soap, const char *URL, const char *action, char *in0, int in1, struct impl__getEUIDBlockResponse *out)
{
	struct impl__getEUIDBlock soap_tmp_impl__getEUIDBlock;
	if (!URL)
		URL = "http://tools:8190/axis/services/EUIDServer";
	if (!action)
		action = "";
	soap_tmp_impl__getEUIDBlock.in0=in0;
	soap_tmp_impl__getEUIDBlock.in1=in1;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_impl__getEUIDBlock(soap, &soap_tmp_impl__getEUIDBlock);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_impl__getEUIDBlock(soap, &soap_tmp_impl__getEUIDBlock, "impl:getEUIDBlock", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	}
	if (soap_connect(soap, URL, action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impl__getEUIDBlock(soap, &soap_tmp_impl__getEUIDBlock, "impl:getEUIDBlock", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_impl__getEUIDBlockResponse(soap, out);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_impl__getEUIDBlockResponse(soap, out, "impl:getEUIDBlockResponse", "impl:getEUIDBlockResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_impl__getEUID(struct soap *soap, const char *URL, const char *action, char *in0, struct impl__getEUIDResponse *out)
{
	struct impl__getEUID soap_tmp_impl__getEUID;
	if (!URL)
		URL = "http://tools:8190/axis/services/EUIDServer";
	if (!action)
		action = "";
	soap_tmp_impl__getEUID.in0=in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_impl__getEUID(soap, &soap_tmp_impl__getEUID);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_impl__getEUID(soap, &soap_tmp_impl__getEUID, "impl:getEUID", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	}
	if (soap_connect(soap, URL, action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impl__getEUID(soap, &soap_tmp_impl__getEUID, "impl:getEUID", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_impl__getEUIDResponse(soap, out);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_impl__getEUIDResponse(soap, out, "impl:getEUIDResponse", "impl:getEUIDResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_impl__hasEUIDNamespace(struct soap *soap, const char *URL, const char *action, char *in0, struct impl__hasEUIDNamespaceResponse *out)
{
	struct impl__hasEUIDNamespace soap_tmp_impl__hasEUIDNamespace;
	if (!URL)
		URL = "http://tools:8190/axis/services/EUIDServer";
	if (!action)
		action = "";
	soap_tmp_impl__hasEUIDNamespace.in0=in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_impl__hasEUIDNamespace(soap, &soap_tmp_impl__hasEUIDNamespace);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_impl__hasEUIDNamespace(soap, &soap_tmp_impl__hasEUIDNamespace, "impl:hasEUIDNamespace", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	}
	if (soap_connect(soap, URL, action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_impl__hasEUIDNamespace(soap, &soap_tmp_impl__hasEUIDNamespace, "impl:hasEUIDNamespace", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
#ifndef WITH_LEANER
	 || soap_putattachments(soap)
#endif
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_impl__hasEUIDNamespaceResponse(soap, out);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_impl__hasEUIDNamespaceResponse(soap, out, "impl:hasEUIDNamespaceResponse", "impl:hasEUIDNamespaceResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_getattachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_END_NAMESPACE(euid)

#ifdef __cplusplus
}
#endif

/* end of euidClient.c */
