#ifndef BIO_PLUS_PLUS_H
#define BIO_PLUS_PLUS_H

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <ctype.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "bio.h"
#include "util++.H"

#include "mers.h"
#include "seq.H"
#include "fasta.H"

#include "fasta-cache.H"
#include "fasta-accessor.H"

#include "chainedSequence.H"

#include "kmer.H"
#include "merstreamfile.H"
#include "merstream.H"
#include "merCovering.H"
#include "merList.H"

#endif  //  BIO_PLUS_PLUS_H

